# Generated by Django 4.0.1 on 2022-03-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_alter_autor_options_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksApp.autor'),
        ),
    ]
